POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Prueba4",
    "username": "prueba4",
    "password": "prueba4"
}

###

POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
}